name: management_church
description: "A Flutter project for church management and livestreaming."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: '>=3.3.0 <4.0.0'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3                          # For making HTTP requests
  cupertino_icons: ^1.0.6                 # iOS style icons
  google_maps_flutter: ^2.2.0             # Google Maps integration
  url_launcher: ^6.1.10                   # For opening URLs
  webview_flutter: ^4.2.1                 # Embedding web content
  table_calendar: ^3.0.9                  # Calendar scheduling
  intl: ^0.18.0                           # Date formatting and internationalization
  shared_preferences: ^2.1.1              # Local storage for user preferences
  flutter_webrtc: ^0.9.28                 # WebRTC for livestreaming
  flutter_ffmpeg: ^0.4.0                  # FFmpeg for video streaming
  web_socket_channel: ^2.1.0              # WebSocket channel for OBS control

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0                   # Linting for code quality

flutter_icons:
    android: true
    ios: true
    image_path: "assets/ic_launcher.png"
    adaptive_icon_background: "#FFA500"
    adaptive_icon_foreground: "assets/ic_launcher.png"


# Flutter assets
flutter:
  uses-material-design: true
  assets:
    - assets/background00.jpg
    - assets/background01.jpg
    - assets/background02.jpg
    - assets/background03.jpg
    - assets/background04.jpg
    - assets/background05.jpg
    - assets/background000.jpg
    - assets/background456.jpg
    - assets/background77.jpg
    - assets/backgroundloading.jpg
    - assets/backgroundscreen.jpg
    - assets/background555.jpg
    - assets/mapbackground.jpg
    - assets/luis.jpg
    - assets/mex.jpg
    - assets/ar.jpg
    - assets/sa.jpg



