name: management_church
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0       # Google Maps plugin for Flutter
  url_launcher: ^6.1.10             # For launching URLs in the browser
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.2.1           # WebView plugin for embedding web pages (updated version)
  table_calendar: ^3.0.9         # Calendar scheduling dependency (updated version)
  intl: ^0.18.0                     # For handling date formatting
  shared_preferences: ^2.1.1        # To save events in local storage (updated version)
  flutter_webrtc: ^0.9.28
  flutter_ffmpeg: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background00.jpg
    - assets/background01.jpg
    - assets/background02.jpg
    - assets/background03.jpg
    - assets/background04.jpg
    - assets/background05.jpg
    - assets/background000.jpg
    - assets/background456.jpg
    - assets/background789.jpg
    - assets/background77.jpg
    - assets/background66.jpg
    - assets/backgroundloading.jpg
    - assets/backgroundls.jpg
    - assets/backgroundscreen.jpg
    - assets/background555.jpg
    - assets/mapbackground.jpg
