name: management_church
description: "A Flutter project for church management and livestreaming."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.2.0
  url_launcher: ^6.0.9
  webview_flutter: ^4.0.0
  webview_flutter_android: ^3.16.3
  webview_flutter_wkwebview: ^3.14.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  flutter_webrtc: ^0.9.28
  flutter_ffmpeg: ^0.4.0
  web_socket_channel: ^2.1.0
  firebase_core: ^2.17.0
  firebase_database: ^10.1.0
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "#FFA500"
  adaptive_icon_foreground: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background00.jpg
    - assets/background01.jpg
    - assets/background02.jpg
    - assets/background03.jpg
    - assets/background04.jpg
    - assets/background05.jpg
    - assets/background000.jpg
    - assets/background456.jpg
    - assets/background77.jpg
    - assets/backgroundloading.jpg
    - assets/backgroundscreen.jpg
    - assets/background555.jpg
    - assets/mapbackground.jpg
    - assets/luis.jpg
    - assets/mex.jpg
    - assets/ar.jpg
    - assets/sa.jpg
    - assets/sf-img.jpg
